name: Check filenames

on:
  push:
    paths:
      - 'masks/**'
      - 'tools/check_filename.py'
      - '.github/workflows/check_filename.yml'
  pull_request:
    paths:
      - 'masks/**'
      - 'tools/check_filename.py'
      - '.github/workflows/check_filename.yml'

jobs:
  stat:
  
    runs-on: ubuntu-latest

    steps:
    - name: Maximize build space
      uses: easimon/maximize-build-space@master      
    - uses: actions/checkout@v3
    - name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pillow tqdm numpy
    - name: Check filenames
      run: |
        python tools/check_filename.py
