name: Don't modify the imgs folder

on:
  push:
    paths:
      - 'imgs/**'      
      - '.github/workflows/dont_modify_imgs.yml'
  pull_request:
    paths:
      - 'imgs/**'      
      - '.github/workflows/dont_modify_imgs.yml'

jobs:
  check_imgs:
  
    runs-on: ubuntu-latest

    steps:
    - name: Maximize build space
      uses: easimon/maximize-build-space@master      
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Check 1st thousand
      run: test $(git diff --name-only HEAD 0266ab9dbef438f36171de9fe3cb7938bb2bd0b2 imgs/0* | wc -l) -eq 0
    - name: Check 2nd thousand
      run: test $(git diff --name-only HEAD 4cee1fb54a016a72af204dd1b8effe4cb007df54 imgs/1* | wc -l) -eq 0
